### ISSUE TITLE
New line in diff

### ISSUE THREAD

**Issue by nitzan-tz** [InfrastructureAsCode-ch/nornir_rich#8]
Hi,

This is excellent plugin but I have issue with printing multi line text from diff variable 

From the following line 
`        print_result(job, vars=["host", "result", "changed", "diff"], severity_level=logging.INFO, expand=True, )`

I get the following output (Hope it is readable in github ) 
The issue is with the diff "'[edit]\n- version 22.1R2.10;\n+ version 21.2R3-S2.9;' │"
Instead of printing 3 lines it print the "\n" charter 
Is there a way to cause it to print the diff correctly ?

```
│ │ │ changed = True                                                   │                                                                                                                    │ │
│ │ │    diff = '[edit]\n- version 22.1R2.10;\n+ version 21.2R3-S2.9;' │                                                                                                                    │ │
│ │ │    host = Host: leaf1-lab                                        │                                                                                                                    │ │
│ │ │  result = None                                                   │     
```

**Comment by nitzan-tz** [comment]
Please see the pool request I add that "fix" this issue
Maybe you have better idea

**Comment by ubaumann** [comment]
Thanks for your contribution. Sorry for the late replay. I am seeing into finding an elegant and generic solution
